### ISSUE TITLE
Greek text

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/BOP#1]
This issue to track progress of insertion of Greek text into bop.txt.

Related issues: 

https://github.com/sanskrit-lexicon/csl-devanagari/issues/40
https://github.com/sanskrit-lexicon/csl-orig/issues/836

**Comment by funderburkjim** [comment]
## proof_greek.txt

Have extracted the greek (and other language) text from bop_main.txt prepared by @Andhrabharati.
And have prepared a file for Holger Teipel-Jahr to proofread the Greek.
The work is done in the [greek directory](https://github.com/sanskrit-lexicon/BOP/tree/main/greek), and
includes as usual a readme file describing the steps.
The file for holger is [proof_greek.txt](https://github.com/sanskrit-lexicon/BOP/blob/main/greek/proof_greek.txt).

I'll communicate this to him -- hope the format of the proof_greek file will be useable for him.

These changes not yet reflected in csl-orig/v02/bop.txt -- will modify this when proofreading step finished.

**Comment by Andhrabharati** [comment]
Pl. see my post (in the csl-devanagari repo) reg. the addl. entry in my version.

**Comment by funderburkjim** [comment]
Note to self:  When holger returns corrected proof_greek.txt,  also take into account [BOP_main-L2.txt](https://github.com/sanskrit-lexicon/csl-devanagari/files/8633290/BOP_main-L2.txt) mentioned in csl-devanagari#40.

**Comment by gasyoun** [comment]
> Holger Teipel-Jahr to proofread the Greek.

Have we heard about him before at Cologne?

**Comment by funderburkjim** [comment]
Our csl-corrections records show that Holger has made 74 correction submissions, starting 03/15/2018.
To MW, PWG, CCS, MWE, PW, and now BOP.

**Comment by funderburkjim** [comment]
Installed the Greek text revisions from @Andhrabharati.
Will deal with revisions from Holger whenever they may arrive.

**Comment by gasyoun** [comment]
> Our csl-corrections records show that Holger has made 74 correction submissions, starting 03/15/2018. To MW, PWG, CCS, MWE, PW, and now BOP.

But we have never contacted him with a list of corrections for proof?

**Comment by Andhrabharati** [comment]
As my L2 file has nothing to do with the greek text, I guess @funderburkjim could implement the corrections in it, without waiting for the "greek proofing" to happen.

**Comment by funderburkjim** [comment]
> we have never contacted him with a list of corrections for proof? 

Correct.  Since he sent (via the user-submission form)  a couple of Greek text additions to BOP, I thought it worth
a shot to ask him for help.  He responded positively.  Current status is that the greek text entries provided by AB have
been sent to him for proof reading.

**Comment by funderburkjim** [comment]
## punctuation after Greek
Recently with Greek text in Benfey, missing punctuation after Greek text fragments was added.
Once there is alignment between the greek text fragments in AB's version and in the CSL version,
then we may further align the character just beyong the ending `</lang>`.

The program (punct.py) doing this punctuation alignment for Benfey, was applied to the Bopp.
Result was about 50 changes. in bop.txt.
(see change_9.txt) in the 'greek' directory.

**Comment by funderburkjim** [comment]
## lang tags in front, addenda
These two sections are currently part of the csl-orig/v02/bop/bop.txt file.
By contrast, Andhrabharati version has separated these into separate files
  (ref: https://github.com/sanskrit-lexicon/csl-devanagari/issues/40)

The fillled in lang tags (greek and otherwise) of these sections in AB's versions
has been applied to the csl bop.txt.

**Comment by drdhaval2785** [comment]
@funderburkjim Any update from Holger? Or @jmigliori or @AnnaRybakovaT may help with the proofreading?

**Comment by AnnaRybakovaT** [comment]
> @AnnaRybakovaT may help with the proofreading?

Dear all,
I know only Modern Greek but I can try to check this file (as well as for BUR).

**Comment by Andhrabharati** [comment]
Anna,

I know no Greek at all (modern or classic). I just tried to identify the letters, accent marks and other notations in the print and put the same in the file. [Of course, I am a quick learner of 'anything' that I come across or take-up.]

From what I noticed in your working all these days, I (and others here) feel you would easily do the intended task here.

**Comment by funderburkjim** [comment]
> Any update from Holger? 

No.

**Comment by AnnaRybakovaT** [comment]
> From what I noticed in your working all these days, I (and others here) feel you would easily do the intended task here.

Thanks for kind words.
I hope soon I will finish my current RegEx task and can do this issue.

Just for information. For one week I will be without connection since I am going to Athens.

**Comment by Andhrabharati** [comment]
@drdhaval2785 

Anna did the proof reading of all the greek words in April '03 and Jim has installed the same (at #4).
[This issue awaits to be closed.]
