### ISSUE TITLE
Additional entry in AB version

### ISSUE THREAD

**Issue by Andhrabharati** [sanskrit-lexicon/BOP#3]
> python prep1.py temp_bop_0.txt temp_bop_ab_1_slp1.txt temp_prep1.txt
> 57719 lines read from temp_bop_0.txt
> 8960 entries found
> 37845 lines read from temp_bop_ab_1_slp1.txt
> 8961 entries found
> 
> There is one more entry in ab version.
>  '3593.1'  This is the cerebral nasal 'Ra' (slp1).
>  bop_0 does not count as headword, but bop_ab does count as headword.
>  Note that other letters are generally not counted as headwords.
>  Solution:  comment out 3593.1

In general, as Jim has mentioned above, BOP has no entries for the letters; but there indeed are such incidences, see--
`<L>3028<pc>116-2a<k1>च्<k2>च्`
`<L>3330<pc>133-a<k1>ज्<k2>ज्`
`<L>7692<pc>340-1a<k1>श्<k2>श्`

Looking at these precedents, I had changed the
`<P>{%De radicibus, quae apud grammaticos a linguali nasali%} {#ण्#} {%incipiunt v. gr.%} 109.`
to a `<L>` type item
`<L>3593.1<pc>146-2a<k1>ण<k2>ण	{#ण#}¦ {%De radicibus, quae apud grammaticos a linguali nasali%} {#ण्#} {%incipiunt v. gr.%} 109.	<LEND>`
 for this ण.

Otherwise, this particular line remains hidden in the txt file-- not coming under any search pattern to the public.

**Comment by Andhrabharati** [comment]
Probably this entry letter could be made ण्, instead of ण as in my file.

**Comment by gasyoun** [comment]
> Looking at these precedents, I had changed the

So it's out of series?

**Comment by Andhrabharati** [comment]
As this entry is separated in the current cdsl file also, the issue is closable now.
