### ISSUE TITLE
Explanation of LS numbers in BOP

### ISSUE THREAD

**Issue by drdhaval2785** [sanskrit-lexicon/BOP#7]
Headword - kumudvat

Current digitization in csl-devanagari
```
<L>2264<pc>077-a<k1>कुमुद्वत्<k2>कुमुद्वत्
{#कुमुद्वत्#}¦ {%n.%} (a {#कुमुद्#} s. {#वत्#}) 1) lotis abundans. RAGH. 4.
19. 2) {%m. n.%} i. q. {#कुमुदिनी#}. AM.
<LEND>
```

AB version
```
<L>2264<pc>077-a<k1>कुमुद्वत्<k2>कुमुद्वत्	{#कुमुद्वत्#}¦ {%n.%} (a {#कुमुद्#} s. {#वत्#}) 1) lotis abundans. RAGH. 4.19. 2) {%m. n.%} i. q. {#कुमुदिनी#}. AM.	<LEND>
```

Questions:

1. Why `4.19. 2` with a space instead of `4.19.2`?
2. Are these ls numbers resolved from bop.txt with help of some regex or are they manually corrected as per text, @andhrabharati?

**Comment by Andhrabharati** [comment]
Does this answer your query, @drdhaval2785 ?
![image](https://github.com/sanskrit-lexicon/BOP/assets/75209130/6d03c26f-e51c-4a29-9ccd-e3464adb005d)

One may note the large space between **19.** and **2)**

The BOP has marked the separate meanings/genders in **x)** style; and there is no third numeric element in Ragh. (it has just **xx.yy** numbers) that could go as a citation!

And finally, I did all these corrections mostly with regex itself.

**Comment by drdhaval2785** [comment]
My request would be for the regexes used by you and order of application thereof, so that I can apply the same to bop.txt and arrive at roughly the same configuration as your file. That would enable me to see substantive changes made by you in Meld. Currently, too many false positives to navigate.

**Comment by Andhrabharati** [comment]
I looked at the BOP file now, and seen that it needs much more work than what I did (mostly filling the blanks) those initial days.

So, i would suggest that a complete overhaul might be preferred from the present cdsl text.

**Comment by drdhaval2785** [comment]
What is the import of the above sentence for me? Should I wait till you complete the overhauling?

**Comment by Andhrabharati** [comment]
I do not know, if and when I might take up the CDSL works again.

I just meant that there is not much use with this L2 version that I had posted earlier, as it did not touch many aspects in the digital text.

So far as the (filled up) lang. strings are concerned, Jim seems to have incorporated them (with later corrections from Anna and myself) in to the CDSL file already.

**Comment by drdhaval2785** [comment]
Ok. I keep it in waiting mode till any further update.

**Comment by Andhrabharati** [comment]
@drdhaval2785 

As Jim has worked on my file at #6 now, probably you could close this issue.
